on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: self-hosted
    name: Trigger rokim_conf repo deploy tash
    steps:
      - name: Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: RomainMichau/rokim_conf
          event-type: trigger-deploy
          client-payload: '{"tag": "hugo_blog", "source":"https://github.com/RomainMichau/hugo_blog"}'
